-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 14:48:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema advertisment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema advertisment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `advertisment` DEFAULT CHARACTER SET cp1256 ;
USE `advertisment` ;

-- -----------------------------------------------------
-- Table `advertisment`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisment`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `req_name` VARCHAR(255) NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `req_name_UNIQUE` (`req_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisment`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisment`.`banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `price` DECIMAL(8,2) NULL,
  `content` LONGTEXT NULL,
  `deleted` TINYINT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`id`)
    REFERENCES `advertisment`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisment`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisment`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_agent` TEXT NULL,
  `ip_address` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  `banner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `banner_id`
    FOREIGN KEY (`id`)
    REFERENCES `advertisment`.`banner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
